site_name: VIC
site_description: Variable Infiltration Capacity Model
site_author: UW Hydro | Computational Hydrology
repo_url: https://github.com/UW-Hydro/VIC
site_url: http://vic.readthedocs.org/
theme: readthedocs
theme_dir: 'docs/custom_rtd_theme'
site_favicon: vic_favicon.jpg
copyright: 2015
docs_dir: docs
site_dir: site
use_directory_urls: true

# TODO:
# Pages: creating a hydrograph, plotting, miscellaneous
# figures
# links
# cant figure out how to hide pages
# decom WIKI
# two basin deliniation pages?
pages:
# Main pages
- Home: 'index.md'
- About:
    - 'Model Overview': 'Overview/ModelOverview.md'
    - 'References': 'Documentation/References.md'
    - 'FAQ': 'FAQ/FAQ.md'
    - 'Contact': 'contact.md'
    - 'Links': 'links.md'
- Documentation:
    - 'User Guide': 'Documentation/UserGuide.md'
    - VIC:
        - 'Basin Delineation': 'Documentation/BasinDelineation.md'
        - 'Inputs': 'Documentation/Inputs.md'
        - 'VIC Modes of Operation': 'Documentation/TechnicalNotes.md'
        - 'Running VIC': 'Documentation/RunVIC.md'
        - 'VIC Output Files': 'Documentation/Outputs.md'
        - 'Post-processing': 'Documentation/PostProcessing.md'
    - Routing:
        - 'Routing Input': 'Documentation/Routing/RoutingInput.md'
        - 'Run Routing': 'Documentation/Routing/RunRouting.md'
        - 'Routing Output': 'Documentation/Routing/RoutingOutput.md'
    - 'Plotting': 'Documentation/Plotting.md'
    - 'Calibration': 'Documentation/Calibration.md'
    - 'VIC Disagg': 'Documentation/VICDisagg.md'
- Development:
    - 'Ongoing Development': 'Development/OngoingDevelopment.md'
    - 'Current Version': 'Development/CurrentVersion.md'
    - 'Archived Versions': 'Development/ArchivedVersions.md'
    - 'Version Summaries': 'Development/VersionSummaries.md'
    - 'Compatability': 'Development/CompatOpt.md'
    - 'Contributing': 'Development/Contributing.md'
    - 'Open Source': 'Development/open-source-philosophy.md'
    - 'Working with Git': 'Development/working-with-git.md'
    - 'Git Workflow': 'Development/git-workflow.md'
- Downloads:
    - Datasets: 'Datasets/Datasets.md'
    - Code: 'SourceCode/Code.md'
- hidden:
    - 'Forcing Data': 'Documentation/ForcingData.md'
    - 'Global Param': 'Documentation/GlobalParam.md'
    - 'Lake Param': 'Documentation/LakeParam.md'
    - 'Prep Lake Param': 'Documentation/PrepLake.md'
    - 'Prep Lake Veg': 'Documentation/PrepLakeVeg.md'
    - 'Snow Band': 'Documentation/SnowBand.md'
    - 'Prepare Elev Band': 'Documentation/PrepElevBand.md'
    - 'Soil Param': 'Documentation/SoilParam.md'
    - 'Prepare Soil Param': 'Documentation/PrepSoilParam.md'
    - 'State File': 'Documentation/StateFile.md'
    - 'Station Location': 'Documentation/StationLocation.md'
    - 'Veg Lib': 'Documentation/VegLib.md'
    - 'Veg Param': 'Documentation/VegParam.md'
    - 'Definitions': 'Documentation/Definitions.md'
    - 'Soiltext': 'Documentation/soiltext.md'
    - 'Output Formatting': 'Documentation/OutputFormatting.md'
    - 'Output Var List': 'Documentation/OutputVarList.md'
    - 'Force Type': 'Documentation/FORCETYPE.md'
    - 'PrepMetInputs': 'Documentation/PrepMetInputs.md'
    - 'GridNCDC': 'Documentation/GridNCDC.md'
    - 'p_disag': 'Documentation/p_disag.md'
    - 'MetData': 'Documentation/MetData.md'
    - 'InputVarList': 'Documentation/InputVarList.md'
    - 'CalibrateMethodOther': 'Documentation/CalibrateMethodOther.md'
    - 'MOCOM': 'Documentation/MOCOM.md'
    - 'CalibrateOther': 'Documentation/CalibrateOther.md'
    - 'CalibrateSnow': 'Documentation/CalibrateSnow.md'
    - 'CalibrateSoil': 'Documentation/CalibrateSoil.md'
    - 'Fraction': 'Documentation/Routing/Fraction.md'
    - 'PrepRoutingParams': 'Documentation/Routing/PrepRoutingParams.md'
    - 'FlowDirection': 'Documentation/Routing/FlowDirection.md'
    - 'PrepRoutingParams': 'Documentation/Routing/PrepRoutingParams.md'
    - 'FlowVelocity': 'Documentation/Routing/FlowVelocity.md'
    - 'PrepRoutingParams': 'Documentation/Routing/PrepRoutingParams.md'
    - 'FlowDiffusion': 'Documentation/Routing/FlowDiffusion.md'
    - 'PrepRoutingParams': 'Documentation/Routing/PrepRoutingParams.md'
    - 'Xmask': 'Documentation/Routing/Xmask.md'
    - 'PrepRoutingParams': 'Documentation/Routing/PrepRoutingParams.md'
    - 'StationLocation': 'Documentation/Routing/StationLocation.md'
    - 'UH': 'Documentation/Routing/UH.md'
    - 'VICNetCDF': 'Documentation/VICNetCDF.md'
    - 'SpatialAggregation': 'Documentation/SpatialAggregation.md'
    - 'TemporalAggregation': 'Documentation/TemporalAggregation.md'
    - 'HowToAddNewOutputVars': 'Documentation/HowToAddNewOutputVars.md'
    - 'HowToAddNewOutputVars': 'Documentation/HowToAddNewOutputVars.md'
    - 'FluxOutputFiles': 'Documentation/FluxOutputFiles.md'
    - 'Modes': 'Documentation/TechnicalNotes/Modes.md'
    - 'Timestep': 'Documentation/TechnicalNotes/Timestep.md'
    - 'Timestepfrozsoil': 'Documentation/TechnicalNotes/Timestepfrozsoil.md'
    - 'GroundHeatFlux': 'Documentation/TechnicalNotes/GroundHeatFlux.md'
    - 'Stability': 'Documentation/TechnicalNotes/Stability.md'
    - 'Radiation': 'Documentation/TechnicalNotes/Radiation.md'
    - 'OtherOutputFiles': 'Documentation/OtherOutputFiles.md'
    - 'DefaultOutputs': 'Documentation/DefaultOutputs.md'
    - 'FrozenSoilText': 'Overview/FrozenSoilText.md'
    - 'SnowBandsText': 'Overview/SnowBandsText.md'
    - 'SnowModelText': 'Overview/SnowModelText.md'
    - 'SnowOutputFile': 'Documentation/SnowOutputFile.md'
    - 'FrozenSoilOutputFile': 'Documentation/FrozenSoilOutputFile.md'
    - 'SnowBandOutputFiles': 'Documentation/SnowBandOutputFiles.md'
    - 'LakeOutputFile': 'Documentation/LakeOutputFile.md'
    - 'LDASOutputFile': 'Documentation/LDASOutputFile.md'


markdown_extensions:
    - toc:
        permalink: True

copyright: 'Copyright &copy; 2015, <a href="http://uw-hydro.github.io/">University of Washington Computational Hydrology Group</a>.'

google_analytics: ['UA-65965729-1', 'vic.readthedocs.org']
